
language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t thiagocf/docker-react-test -f Dockerfile.dev . # after -t, dockerhub-profile/name-of-github-project

script:
  - docker run -e CI=true thiagocf/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react-test"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-sa-east-1-108401012963"
  bucket_path: "Dockerreacttest-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
